### ISSUE TITLE
Feature request: to be able to preview and record like in the GoPro app.

### ISSUE THREAD

**Issue by garydelarosausername** [KonradIT/GoProStream#11]
I think that's really cool! I have quite some time on my hands. I don't code though. I only know very basic, and the most I know in is in Python. I'd gladly help though. Hopefully I can help to make this process/feature request faster to reality! :D 

Sorry for sounding naive, but really I think this feature is neat! I've tried doing this by having two versions of the script: one that does preview and the other records. Doesn't work, because there should only be one instance of the script running at anytime.

**Comment by KonradIT** [comment]
Doesn't work because two ffmpeg instances cannot use udp://:8554 at once.

**Comment by garydelarosausername** [comment]
@KonradIT Oh ok! Thanks!
