### ISSUE TITLE
How do I run Record and Preview from anywhere in the terminal?

### ISSUE THREAD

**Issue by garydelarosausername** [KonradIT/GoProStream#13]
I could've set it already to $PATH if it was only an executable, like downloading youtube-dl from it's [official website](https://rg3.github.io/youtube-dl/). But it comes with a README and a .rb. I think I may have to do some compilation and then make it an executable - removing the extension too. Then only I think I can set a $PATH for it and be able to call it from anywhere in the terminal. I think that's really awesome! :D 

Looking forward to you guys' replies! :D

**Comment by KonradIT** [comment]
Off-topic, you can call the **python** script from anywhere, so if I have the script in /home/$USER/gopro/goprostream.py I can just call `python /home/$USER/gopro/goprostream.py`

**Comment by garydelarosausername** [comment]
@KonradIT Oh ok. Not necessarily what I was thinking of. Since you said it's OT, I'll have this discussed somewhere else. Thanks!
