### ISSUE TITLE
Video recorded with GoProStream.py doesn't play in Windows 10.

### ISSUE THREAD

**Issue by garydelarosausername** [KonradIT/GoProStream#14]
I play my 4k videos in Windows 10 because it plays there properly. There's sound, but I don't see anything.
Help please? What might be causing this?

Thanks!

**Comment by KonradIT** [comment]
Sound is only available in video mode.

**Comment by garydelarosausername** [comment]
@KonradIT You mean, I'm stuck with playing the videos recorded via the script in Linux? At least right now?

**Comment by KonradIT** [comment]
Do you mean the script or videos from the camera?

**Comment by garydelarosausername** [comment]
The videos recorded and saved where specified: SAVE_LOCATION="~/<dir>" something like that. You get it.
