### ISSUE TITLE
Preview delays too much after first recording via the camera shutter button.

### ISSUE THREAD

**Issue by garydelarosausername** [KonradIT/GoProStream#15]
Preview delays too much after the first recording. Delay before first recording was fine - that's the live feed (RECORD and SAVE are FALSE), like that delay in the GoPro app (as said too in the docs. of the script). After the first recording via the shutter button on the camera, Preview lags/freezes and upon stopping recording via the camera shutter button, delay is doubled, even tripled.

Help please?

Thanks!

**Comment by garydelarosausername** [comment]
[I think I may have found a fix](https://www.reddit.com/r/gopro/comments/2md8hm/how_to_livestream_from_a_gopro_hero4/cr1b193/). Where do I put the parameters though?

**Comment by KonradIT** [comment]
Disable all flags.
