### ISSUE TITLE
GoPro Hero 6 5GHz WiFi

### ISSUE THREAD

**Issue by Crypter** [KonradIT/GoProStream#32]
As you may (or not) know, the GoPro Hero 6 is region locked for its 5GHz Wifi. Is there are chance we could override these settings via its API? I found some strings regarding the API possibilities, but I couldn't make use of them.

Do you have time to take a look at this?

Also, should we expect autoexec.sh for the Hero 6? I found C:\autoexec.sh string in the fw, but I couldn't get it to execute. Maybe I'm doing something wrong, but both echo and reboot commands didn't work.

Thank you for your efforts!

**Comment by KonradIT** [comment]
Hi,

New autoexec.ash replacemet is [gpauto](https://github.com/konradit/gpauto)

Setting 5ghz wifi on Hero6 in Europe is illegal.

**Comment by Crypter** [comment]
Thx for the heads up for gpauto, I'll take a look at it!

On a different side note, the lower 5GHz band is available in Europe (chan 36 - 48). The remark that it is for "indoor use" is applicable only in certain countries. In Macedonia there are 5Ghz outdoor WiFi links used on regular basis - the band is open for use.

However, fsck those guys, I'll try my best to enable it, even if it takes firmware modifications.

**Comment by KonradIT** [comment]
What have you tried? I don't have a Hero 6.

**Comment by Crypter** [comment]
So far I'm still gathering tools. I still haven't managed to unpack the firmware (I can share the file if needed, since it requires serial to download). At the moment I'm poking with regex for shell script strings, whatever contains "5GHz" in its line and stuff like that.

Apparently, they disable 5GHz for "Region 2" (seems like DVD Region 2, which is Europe and small part of Asia and Aftica). And the default mode in this camera is 2.4Ghz and is set in their hostapd.conf file (or something equal to that).

If I had telnet access to this thing I could do wonders with it...

**Comment by KonradIT** [comment]
Umm...

https://gopro.com/content/dam/help/hero6-black/manuals/HERO6Black_UM_ENG_REVB.pdf

Seems like you can change the WIfi band in the camera itself.

**Comment by Crypter** [comment]
That menu does not exist at all... I might try forcing some older firmware to see what comes up, but I don't think that will change anything. I never found someone that lost the option, people just didn't have it.

**Comment by KonradIT** [comment]
You can try with command/wireless/band/select (set to ?p=1/2 etc...)

**Comment by Crypter** [comment]
`{
  "status": {
    "1": 1,
    "2": 3,
    "3": 0,
    "4": 255,
    "6": 0,
    "8": 0,
    "9": 0,
    "10": 0,
    "11": 0,
    "13": 0,
    "14": 0,
    "15": 0,
    "16": 0,
    "17": 1,
    "19": 0,
    "20": 0,
    "21": 0,
    "22": 0,
    "23": 0,
    "24": 0,
    "26": 0,
    "27": 0,
    "28": 82,
    "29": "",
    "30": "GP25460253",
    "31": 0,
    "32": 0,
    "33": 0,
    "34": 8663,
    "35": 8267,
    "36": 0,
    "37": 2,
    "38": 0,
    "39": 2,
    "40": "%12%08%11%11%1C%25",
    "41": 0,
    "42": 0,
    "43": 0,
    "44": 0,
    "45": 0,
    "46": 0,
    "47": 1,
    "48": 1,
    "49": 0,
    "54": 62093952,
    "55": 1,
    "56": 4,
    "57": 73358,
    "58": 0,
    "59": 0,
    "60": 500,
    "61": 2,
    "62": 0,
    "63": 0,
    "64": 4331,
    "65": 0,
    "66": 0,
    "67": 0,
    "68": 0,
    "69": 1,
    "70": 93,
    "71": 12,
    "72": 17,
    "73": 20,
    "74": 0,
    "75": 0,
    "76": 1,
    "77": 1,
    "78": 1,
    "79": 0,
    "81": 0,
    "82": 1,
    "83": 1
  },
  "settings": {
    "1": 0,
    "2": 9,
    "3": 5,
    "4": 0,
    "5": 0,
    "6": 1,
    "8": 1,
    "10": 1,
    "11": 0,
    "12": 1,
    "13": 1,
    "14": 0,
    "15": 4,
    "16": 0,
    "17": 0,
    "19": 0,
    "21": 0,
    "22": 0,
    "23": 0,
    "24": 0,
    "25": 0,
    "26": 0,
    "27": 0,
    "28": 0,
    "29": 0,
    "30": 0,
    "31": 0,
    "32": 10,
    "34": 0,
    "35": 0,
    "36": 0,
    "37": 0,
    "38": 0,
    "39": 0,
    "40": 0,
    "41": 13,
    "42": 8,
    "43": 0,
    "44": 8,
    "45": 8,
    "46": 0,
    "47": 0,
    "48": 0,
    "51": 1,
    "52": 0,
    "54": 1,
    "57": 0,
    "59": 6,
    "60": 0,
    "61": 0,
    "62": 0,
    "64": 0,
    "65": 0,
    "66": 0,
    "67": 0,
    "68": 0,
    "69": 0,
    "70": 0,
    "71": 0,
    "73": 0,
    "75": 0,
    "76": 0,
    "78": 1,
    "80": 0,
    "81": 0,
    "82": 0,
    "83": 1,
    "84": 0,
    "85": 0,
    "86": 0,
    "87": 0,
    "88": 100,
    "89": 12,
    "91": 2,
    "92": 12,
    "94": 0,
    "95": 1,
    "96": 0,
    "97": 0,
    "98": 0,
    "99": 0,
    "100": 0,
    "102": 8,
    "103": 3,
    "104": 0
  }
}`
