### ISSUE TITLE
Change Resolution?

### ISSUE THREAD

**Issue by ardianumam** [KonradIT/GoProStream#41]
Hi,

First, thanks for this repo. It helps me a lot. I have a question, how can I change the resolution on video streaming? I currently get resolution of 864x480. Thanks.

**Comment by KonradIT** [comment]
You can use gopro-py-api

**Comment by ardianumam** [comment]
Already answered [here](https://github.com/KonradIT/goprowifihack/issues/92#issuecomment-500711204), thanks.
