### ISSUE TITLE
import error on module request - streaming session 4 by the py script

### ISSUE THREAD

**Issue by 5perseo** [KonradIT/GoProStream#8]
Opening the sessione by the app is possible to streaming by ffmpeg. Without it the cam doesn't respond on url command ...
running the GoProStreaming.py file error on line 17 appear...

ImportError: no module named request

![immagine](https://user-images.githubusercontent.com/30870535/29128739-ffbed540-7d24-11e7-8d3d-75237877d6f0.png)

**Comment by KonradIT** [comment]
you're using 2.7, use Python 3.5 and make sure urrlib is installed.

**Comment by 5perseo** [comment]
Ok little step behind,,,
after py run an error with ffplay appear although they are all in the same folder.
![immagine](https://user-images.githubusercontent.com/30870535/29140652-881c211a-7d4b-11e7-9f69-4a05ce114a2c.png)
launching
ffplay -an -fflags nobuffer -f:v mpegts -probesize 8192 rtp://10.5.5.9:8554
it starts to stream perfectly ... but i would fix...

**Comment by 5perseo** [comment]
It works-
After script run launching the command:
ffplay -fflags nobuffer -f:v mpegts -probesize 8192 rtp://10.5.5.9:8554
or
ffplay udp://10.5.5.9:8554
it streams properly.
But it doesn't start if a moment before run the script i don't press the
button on the back... i've to awake manually the cam!! . I think there's
something wrong according the instruction... i thin also it sholuld be
possible to awake the camera like the app does... correct?

2017-08-09 17:17 GMT+02:00 Konrad Iturbe <notifications@github.com>:

**Comment by KonradIT** [comment]
You need a wakeonlan command to turn it on

**Comment by 5perseo** [comment]
uhm the "magic packet"i'm reading in your posts.. ..? ok i'll study on the net how get it...
one question on feasibility of a project that get me here?
All this is catching me sleepy hours for one hobby project I've in mind... I would command the gopro underwater.
The idea is to get closer the camera an access point (encloused ip68 of course) in order to get signal wired within a cat6 cable... is it possible? should I change the script in order to take in account the access point, the port etc or it's straightforward? I'm thinking to this device:
TP-Link TL-WR802N Nano Router Wi-Fi, 300 Mbps, Router, Repeater, Client, AP e WISP .

if this is OT for GitHub I'd appreciate a PM on mainieri13@gmail.com.
As you said on a post all this it's not only an informatic excercise but has pratical application and action cam are not only for sport!

thanks in advance...

**Comment by 5perseo** [comment]
using your API i can turn on the camera!



2017-08-09 23:38 GMT+02:00 Konrad Iturbe <notifications@github.com>:
