### ISSUE TITLE
Ffmpeg doesn't open the preview window 

### ISSUE THREAD

**Issue by Maxiride** [KonradIT/GoProStream#9]
I've tried the script under Linux successfully, however under windows (with all the prerequisites satisfied) the script runs, detects the gopro and start "the stream" but no live window opens automatically like under Linux.

No errors are shown in the console so I don't know how to help debug the issue at the moment. 

I've also tried to run the script from the shell with administrator privileges. 

![shell](https://user-images.githubusercontent.com/3630857/30521922-36d46d94-9bc8-11e7-82ba-31f480a1322e.png)

**Comment by KonradIT** [comment]
Windows network limitation.

**Comment by Maxiride** [comment]
@KonradIT are there workarounds for a live feed under windows then?
